apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: my-vote
    meta.helm.sh/release-namespace: vote
  labels:
    app: vote
    app.kubernetes.io/managed-by: helm
  name: vote
  namespace: vote
spec:
  replicas: {{ .Values.image_vote.replicas}}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: "{{ .Values.image_vote.repository}}:{{ .Values.image_vote.tag}}"
        imagePullPolicy: {{ .Values.image_vote.pullPolicy }}
        name: vote
        ports:
        - containerPort: 80
          name: vote
